service: nestjs-typescript-challenge

frameworkVersion: "3"

useDotenv: true

# plugins:
#   - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1024 # optional, in MB, default is 1024
  timeout: 6 # optional, in seconds, default is 6
  stage: dev
  region: us-east-2
  environment: 
    PORT: ${PORT}
    JWT_SECRET: ${JWT_SECRET}
    DB_HOST: ${DB_HOST}
    DB_PORT: ${DB_PORT}
    DB_USER: ${DB_USER}
    DB_PASS: ${DB_PASS}
    DB_DATABASE: ${DB_DATABASE}

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /{proxy+}

custom:
  optimize:
    external: ['swagger-ui-dist']